FROM php:8.3-apache

# تثبيت الـ extensions المطلوبة لـ Laravel
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    zip \
    unzip \
    git \
    curl \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip mysqli \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# تفعيل mod_rewrite
RUN a2enmod rewrite

# إعداد Apache
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

# صلاحيات
WORKDIR /var/www/html
RUN chown -R www-data:www-data /var/www/html 

EXPOSE 80
CMD ["apache2-foreground"]
